# Generated by Django 5.2.4 on 2025-07-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_equipo_cargo_equipo_profesionalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='investigacion/fotos/'),
        ),
    ]

