# Generated by Django 5.2.4 on 2025-07-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_investigacion_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones/imagenes/'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='video',
            field=models.FileField(blank=True, help_text='Opcional. Solo formatos mp4/webm', null=True, upload_to='publicaciones/videos/'),
        ),
    ]

