# Generated by Django 5.2.4 on 2025-07-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_publicacionimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fecha_cierre',
            field=models.DateField(blank=True, help_text='Fecha de cierre del evento (opcional)', null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='archivo',
            field=models.FileField(blank=True, help_text='Archivos adicionales para descargar', null=True, upload_to='eventos/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='pdf',
            field=models.FileField(blank=True, help_text='Archivo PDF del evento', null=True, upload_to='eventos/'),
        ),
    ]

