# Generated by Django 5.2.5 on 2025-09-23 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_bolsatrabajo_delete_contacto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacionimagen',
            name='publicacion',
            field=models.ForeignKey(db_column='publicacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.publicacion'),
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=150)),
                ('afiliacion', models.CharField(blank=True, default='', max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autores_perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PublicacionAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('rol', models.CharField(blank=True, choices=[('autor', 'Autor'), ('corresp', 'Autor de correspondencia'), ('editor', 'Editor')], default='', max_length=20)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.autor')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publicacion')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('publicacion', 'autor')},
            },
        ),
        migrations.AddField(
            model_name='publicacion',
            name='autores_detalle',
            field=models.ManyToManyField(blank=True, related_name='publicaciones', through='core.PublicacionAutor', to='core.autor'),
        ),
    ]

