# Generated by Django 5.2.5 on 2025-09-25 22:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_publicacionimagen_publicacion_autor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
                'db_table': 'nivel',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TemaInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_interes', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Tema de interÃ©s',
                'verbose_name_plural': 'Temas de interÃ©s',
                'db_table': 'tema_interes',
                'ordering': ['descripcion_interes'],
            },
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_universidad', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Universidad',
                'verbose_name_plural': 'Universidades',
                'db_table': 'universidad',
                'ordering': ['descripcion_universidad'],
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='dni',
            field=models.CharField(blank=True, help_text='SÃ³lo nÃºmeros; 7â€“9 dÃ­gitos.', max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='DNI debe contener sÃ³lo nÃºmeros (7 a 9 dÃ­gitos).', regex='^\\d{7,9}$')]),
        ),
        migrations.AlterModelTable(
            name='equipo',
            table='equipo',
        ),
        migrations.AddField(
            model_name='equipo',
            name='nivel',
            field=models.ForeignKey(blank=True, db_column='id_nivel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros', to='core.nivel'),
        ),
        migrations.CreateModel(
            name='EquipoInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('equipo', models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.CASCADE, related_name='equipo_intereses', to='core.equipo')),
                ('tema_interes', models.ForeignKey(db_column='id_tema_interes', on_delete=django.db.models.deletion.CASCADE, related_name='equipo_intereses', to='core.temainteres')),
            ],
            options={
                'db_table': 'equipo_interes',
                'ordering': ['orden', 'id'],
                'unique_together': {('equipo', 'tema_interes')},
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='intereses',
            field=models.ManyToManyField(blank=True, related_name='miembros', through='core.EquipoInteres', to='core.temainteres'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='universidad',
            field=models.ForeignKey(blank=True, db_column='id_universidad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros', to='core.universidad'),
        ),
    ]

