# Generated by Django 5.2.2 on 2025-09-26 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_nivel_temainteres_universidad_equipo_dni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='profesionalidad',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='universidad',
        ),
        migrations.AddField(
            model_name='equipo',
            name='nivel_descripcion',
            field=models.TextField(blank=True, verbose_name='DescripciÃ³n del Nivel de FormaciÃ³n'),
        ),
        migrations.AddField(
            model_name='equipointeres',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='DescripciÃ³n del InterÃ©s'),
        ),
        migrations.CreateModel(
            name='EquipoUniversidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, verbose_name='DescripciÃ³n (ej: TÃ­tulo obtenido)')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('equipo', models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.CASCADE, related_name='equipo_universidades', to='core.equipo')),
                ('universidad', models.ForeignKey(db_column='id_universidad', on_delete=django.db.models.deletion.CASCADE, related_name='equipo_universidades', to='core.universidad')),
            ],
            options={
                'db_table': 'equipo_universidad',
                'ordering': ['orden', 'id'],
                'unique_together': {('equipo', 'universidad')},
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='universidades',
            field=models.ManyToManyField(blank=True, related_name='miembros', through='core.EquipoUniversidad', to='core.universidad'),
        ),
        migrations.CreateModel(
            name='Profesionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='TÃ­tulo del Rol o Cargo')),
                ('descripcion', models.TextField(blank=True, verbose_name='DescripciÃ³n del Rol')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('equipo', models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.CASCADE, related_name='profesionalidades', to='core.equipo')),
            ],
            options={
                'verbose_name': 'Profesionalidad',
                'verbose_name_plural': 'Profesionalidades',
                'db_table': 'equipo_profesionalidad',
                'ordering': ['orden', 'id'],
            },
        ),
    ]

