# Generated by Django 5.2.2 on 2025-09-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_equipo_profesionalidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='email_publico',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Email PÃºblico de Contacto'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='URL de LinkedIn'),
        ),
    ]

