# Generated by Django 5.2.2 on 2025-09-26 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_equipo_email_publico_equipo_linkedin_url'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='equipo',
            table='cuerpo_equipo',
        ),
        migrations.AlterModelTable(
            name='equipointeres',
            table='cuerpo_equipo_interes',
        ),
        migrations.AlterModelTable(
            name='equipouniversidad',
            table='cuerpo_equipo_universidad',
        ),
        migrations.AlterModelTable(
            name='evento',
            table='cuerpo_evento',
        ),
        migrations.AlterModelTable(
            name='investigacion',
            table='cuerpo_investigacion',
        ),
        migrations.AlterModelTable(
            name='nivel',
            table='cuerpo_nivel',
        ),
        migrations.AlterModelTable(
            name='noticia',
            table='cuerpo_noticia',
        ),
        migrations.AlterModelTable(
            name='profesionalidad',
            table='cuerpo_equipo_profesionalidad',
        ),
        migrations.AlterModelTable(
            name='publicacion',
            table='cuerpo_publicacion',
        ),
        migrations.AlterModelTable(
            name='publicacionautor',
            table='cuerpo_publicacionautor',
        ),
        migrations.AlterModelTable(
            name='publicacionimagen',
            table='cuerpo_publicacionimagen',
        ),
        migrations.AlterModelTable(
            name='temainteres',
            table='cuerpo_tema_interes',
        ),
        migrations.AlterModelTable(
            name='universidad',
            table='cuerpo_universidad',
        ),
    ]

