# Generated by Django 5.2.2 on 2025-09-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_equipo_table_alter_equipointeres_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='color_perfil',
            field=models.CharField(blank=True, default='#1a4d2e', help_text='Color en formato hexadecimal (ej. #1a4d2e) para la vista de perfil.', max_length=7, verbose_name='Color de Perfil'),
        ),
    ]

