# Generated by Django 5.2.4 on 2025-10-02 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_equipo_color_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='video',
            field=models.CharField(blank=True, help_text='URL de YouTube, Vimeo o archivo de video', max_length=200, verbose_name='URL del Video'),
        ),
        migrations.CreateModel(
            name='NoticiaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.CharField(blank=True, max_length=200, verbose_name='URL de la Imagen')),
                ('orden', models.IntegerField(default=0)),
                ('noticia', models.ForeignKey(db_column='noticia_id', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.noticia')),
            ],
            options={
                'db_table': 'cuerpo_noticia_imagen',
                'ordering': ['orden'],
            },
        ),
    ]

