# Generated by Django 5.2.4 on 2025-10-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_noticia_video_noticiaimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/', verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='noticiaimagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/galeria/', verbose_name='Imagen'),
        ),
    ]

