# Generated by Django 5.2.4 on 2025-10-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_noticia_imagen_alter_noticiaimagen_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la noticia'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='video',
            field=models.FileField(blank=True, help_text='Archivo de video (MP4, WebM, etc.)', null=True, upload_to='noticias/videos/', verbose_name='Video'),
        ),
    ]

