# Generated by Django 5.2.4 on 2025-10-02 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_noticia_fecha_alter_noticia_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigacion',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='investigacion',
            name='foto',
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la investigaciÃ³n'),
        ),
        migrations.CreateModel(
            name='InvestigacionArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='investigaciones/archivos/', verbose_name='Archivo')),
                ('nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre del archivo')),
                ('orden', models.IntegerField(default=0)),
                ('investigacion', models.ForeignKey(db_column='investigacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='core.investigacion')),
            ],
            options={
                'db_table': 'cuerpo_investigacion_archivo',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='InvestigacionFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='investigaciones/fotos/', verbose_name='Foto')),
                ('orden', models.IntegerField(default=0)),
                ('investigacion', models.ForeignKey(db_column='investigacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.investigacion')),
            ],
            options={
                'db_table': 'cuerpo_investigacion_foto',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='InvestigacionIntegrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, max_length=100, verbose_name='Rol en la investigaciÃ³n')),
                ('orden', models.IntegerField(default=0)),
                ('integrante', models.ForeignKey(db_column='integrante_id', on_delete=django.db.models.deletion.CASCADE, to='core.equipo')),
                ('investigacion', models.ForeignKey(db_column='investigacion_id', on_delete=django.db.models.deletion.CASCADE, to='core.investigacion')),
            ],
            options={
                'db_table': 'cuerpo_investigacion_integrante',
                'ordering': ['orden'],
                'unique_together': {('investigacion', 'integrante')},
            },
        ),
        migrations.AddField(
            model_name='investigacion',
            name='integrantes',
            field=models.ManyToManyField(blank=True, related_name='investigaciones_participadas', through='core.InvestigacionIntegrante', to='core.equipo'),
        ),
    ]

