# Generated by Django 5.2.2 on 2025-10-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_investigacion_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='investigaciones/portadas/', verbose_name='Imagen de portada'),
        ),
        migrations.AddField(
            model_name='investigacion',
            name='video_portada',
            field=models.FileField(blank=True, help_text='Archivo de video (MP4, WebM, etc.)', null=True, upload_to='investigaciones/videos/', verbose_name='Video de portada'),
        ),
    ]

