# Generated by Django 5.2.2 on 2025-10-02 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_investigacion_imagen_portada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacionimagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones/imagenes/', verbose_name='Imagen'),
        ),
        migrations.CreateModel(
            name='PublicacionArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='publicaciones/archivos/', verbose_name='Archivo')),
                ('nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre del archivo')),
                ('orden', models.IntegerField(default=0)),
                ('publicacion', models.ForeignKey(db_column='publicacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='core.publicacion')),
            ],
            options={
                'db_table': 'cuerpo_publicacion_archivo',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PublicacionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='publicaciones/videos/', verbose_name='Video')),
                ('orden', models.IntegerField(default=0)),
                ('publicacion', models.ForeignKey(db_column='publicacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.publicacion')),
            ],
            options={
                'db_table': 'cuerpo_publicacionvideo',
                'ordering': ['orden'],
            },
        ),
    ]

