# Generated by Django 5.2.2 on 2025-10-02 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_publicacionimagen_imagen_publicacionarchivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='eventos/archivos/', verbose_name='Archivo')),
                ('nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre del archivo')),
                ('orden', models.IntegerField(default=0)),
                ('evento', models.ForeignKey(db_column='evento_id', on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='core.evento')),
            ],
            options={
                'db_table': 'cuerpo_evento_archivo',
                'ordering': ['orden', 'id'],
            },
        ),
    ]

