# Generated by Django 5.2.2 on 2025-10-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_eventoarchivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='color',
            field=models.CharField(blank=True, default='#2c5530', help_text='Color hex para acento, ej: #2c5530', max_length=7),
        ),
        migrations.AddField(
            model_name='evento',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/portadas/', verbose_name='Imagen de portada'),
        ),
    ]

