# Generated by Django 5.2.7 on 2025-10-30 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_evento_color_evento_imagen_portada'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacionIntegrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, max_length=100, verbose_name='Rol en la publicaciÃ³n')),
                ('orden', models.IntegerField(default=0)),
                ('integrante', models.ForeignKey(db_column='integrante_id', on_delete=django.db.models.deletion.CASCADE, to='core.equipo')),
                ('publicacion', models.ForeignKey(db_column='publicacion_id', on_delete=django.db.models.deletion.CASCADE, to='core.publicacion')),
            ],
            options={
                'db_table': 'cuerpo_publicacion_integrante',
                'ordering': ['orden'],
                'unique_together': {('publicacion', 'integrante')},
            },
        ),
        migrations.AddField(
            model_name='publicacion',
            name='integrantes',
            field=models.ManyToManyField(blank=True, related_name='publicaciones_participadas', through='core.PublicacionIntegrante', to='core.equipo'),
        ),
    ]
